<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Store_System</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Extentions\" />
    <Folder Include="Iterators\" />
    <Folder Include="Exceptions\" />
    <Folder Include="Reports\" />
  </ItemGroup>

</Project>
